# Generated by Django 6.0.6 on 2026-06-14 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeDownloadToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResumeLead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recruiter", "Recruiter"),
                            ("founder", "Founder"),
                            ("engineer", "Engineer"),
                            ("student", "Student"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=255)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hiring", "Hiring"),
                            ("collaboration", "Collaboration"),
                            ("research", "Researching Candidate"),
                            ("learning", "Learning"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
