# Generated by Django 6.0.6 on 2026-06-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="article",
            managers=[],
        ),
    ]
