# Generated by Django 6.0.6 on 2026-06-14 02:32

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_featured"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={"verbose_name_plural": "Technologies"},
        ),
        migrations.AlterField(
            model_name="technology",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="technologies/icons/",
                validators=[projects.models.validate_svg],
            ),
        ),
    ]
